<a href="https://colab.research.google.com/github/BSanandu88/Programming-Data-structures-and-Algorithms-in-Python/blob/main/PDSA_Week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Grpa 3**

In [ ]:
# class Queue:
#   def __init__(self):
#     self.queue = []
  
#   def isempty(self):
#     return self.queue == []
  
#   def addq(self,v):
#     self.queue.append(v)
  
#   def delq(self):
#     v = None
#     if not self.isempty():
#       v = self.queue[0]
#       self.queue = self.queue[1:]
#     return v

def find_northmost_city(AList):
  destinations = []
  for dest_list in AList.values():
    dest_cities = [city for city in dest_list]
    destinations += dest_cities
  northmost_city = [city for city in AList.keys() if city not in destinations]
  return northmost_city[0]

def allPathsFound(paths,AList):
  for path in paths:
    if AList[path[-1]] != []:
      return False
  return True

def findAllPaths(AList):
  curr = find_northmost_city(AList)
  path = [curr]
  paths = [path]
  while not allPathsFound(paths,AList):
    paths2 = paths.copy()
    paths = []
    for path in paths2:
      curr = path[-1]
      if AList[curr] == []:
        paths.append(path)
        continue
      for node in AList[curr]:
        if node in path:
          continue
        else:
          paths.append(path+[node])
  return paths


def longJourney(AList):
    paths = findAllPaths(AList)
    max_path_length = max([len(path) for path in paths])
    for path in paths:
      if len(path) == max_path_length:
        return path




In [1]:
edges = [(0,1),(0,4),(1,2),(2,0),
(3,4),(3,6),(4,0),(4,3),
(4,7),(5,3),(5,7),
(6,5),(7,4),(7,8),
(8,5),(8,9),(9,8)]

import numpy as np
A = np.zeros(shape=(10,10))

for (i,j) in edges:
  A[i,j] = 1
print(A)

[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [2]:
def neigbours(A,i):
  nbrs = []
  (rows,cols) = A.shape
  for j in range(cols):
    if(A[i,j] == 1):
      nbrs.append(j)
  return nbrs

print(neigbours(A,7))

[4, 8]


In [3]:
# Adjacency List
Alist = {}
for i in range(10):
  Alist[i] = []
for (i,j) in edges:
  Alist[i].append(j)

print(Alist)

{0: [1, 4], 1: [2], 2: [0], 3: [4, 6], 4: [0, 3, 7], 5: [3, 7], 6: [5], 7: [4, 8], 8: [5, 9], 9: [8]}


In [10]:
# Breadth First Search
class Queue:
  def __init__(self):
    self.queue = []
  def addq(self,v):
    self.queue.append(v)
  def delq(self):
    v = None
    if not self.isempty():
      v = self.queue[0]
      self.queue = self.queue[1:]
    return (v)
  def isempty(self):
    return (self.queue == [])
  def __str__(self):
    return (str(self.queue))


q = Queue()
for i in range(3):
  q.addq(i)
  print(q)
print(q.isempty())

for j in range(3):
  print(q.delq(),q)
print(q.isempty())

def BFS(Amat,v):
  (rows,cols) = Amat.shape
  visited = {}
  for i in range(rows):
    visited[i] = False
  q1 = Queue()
  visited[v] = True
  q1.addq(v)

  while(not q1.isempty()):
    j = q1.delq()
    for k in neigbours(Amat,j):
      if(not visited[k]):
        visited[k] = True
        q1.addq(k)
  return visited

print(BFS(A,0))

[0]
[0, 1]
[0, 1, 2]
False
0 [1, 2]
1 [2]
2 []
True
{0: True, 1: True, 2: True, 3: True, 4: True, 5: True, 6: True, 7: True, 8: True, 9: True}
